### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by vvsevolodovich** [epam/CoroutinesCache#2]
There is not such interface or class Cache in the library. However the example suggests the following: 

`val coroutines: Cache = CoroutinesCache(cacheParams: CacheParams, scope: CoroutineScope)
`
This should be changed to 

`val coroutines: CoroutinesCache = CoroutinesCache(cacheParams: CacheParams, scope: CoroutineScope)`

or simply 
`
val cache = CoroutinesCache(cacheParams: CacheParams, scope: CoroutineScope)`

**Comment by ahulyk** [comment]
Related to doc:
`Provide the data from RxCache`
We do not have `RxCache` here :)

**Comment by Dartlexx** [comment]
Fixed it in last pull request
